import { Schema, model } from "mongoose";
import { IGoal } from "../types/schema";

const goalSchema = new Schema<IGoal>(
  {
    user_id: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
    content: {
      type: String,
      required: true,
    },
    tips: {
      // this field store tips generated by AI. ex] 1.this... 2. the...
      type: String,
    },
    progress: {
      type: Number, //1-10 number
      default: 0,
    },
    is_pin: {
      type: Boolean, //1-10 number
    },
  }
);

export default model<IGoal>("Goal", goalSchema);
